#!/bin/bash
#Provide the default parameters used by the image.

echo -n "docker run -ti --rm \
	-h \$(basename \${0}) \
	-w \$PWD -v \$PWD:\$PWD \
	-v /etc/localtime:/etc/localtime:ro \
	-v \$HOME/.ssh:\$HOME/.ssh -v \$SSH_AUTH_SOCK:\$SSH_AUTH_SOCK -e SSH_AUTH_SOCK \
	-e USER -e UID=\$(id --user) -e GID=\$(id --group) \
	-v \$(which docker):\$(which docker) -v /var/run/docker.sock:/var/run/docker.sock \
	$@ \
	cell/cvim"

